title: vida
url: "http://ericlyunqi.github.io"
baseurl: "/vida"      
github_repo: "https://github.com/EricLYunqi/EricLYunqi.github.io.git" 


date_format: "%Y-%m-%d"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics:
disqus_shortname: