var hierarchy =
[
    [ "Block", "classBlock.html", null ],
    [ "BlockerUtil", "classBlockerUtil.html", null ],
    [ "CalculateFeature", "classCalculateFeature.html", null ],
    [ "combination1", "structcombination1.html", null ],
    [ "combination2", "structcombination2.html", null ],
    [ "combination_p1", "structcombination__p1.html", null ],
    [ "combination_p2", "structcombination__p2.html", null ],
    [ "CSVReader", "classCSVReader.html", null ],
    [ "simjoin_entitymatching.utils.datasets.Dataset", "classsimjoin__entitymatching_1_1utils_1_1datasets_1_1Dataset.html", null ],
    [ "simjoin_entitymatching.utils.datasets.DataSettings", "classsimjoin__entitymatching_1_1utils_1_1datasets_1_1DataSettings.html", null ],
    [ "simjoin_entitymatching.value_matcher.doc2vec.Doc2Vec", "classsimjoin__entitymatching_1_1value__matcher_1_1doc2vec_1_1Doc2Vec.html", null ],
    [ "DSU", "structDSU.html", null ],
    [ "simjoin_entitymatching.value_matcher.utils.DSU", "classsimjoin__entitymatching_1_1value__matcher_1_1utils_1_1DSU.html", null ],
    [ "ExactJoin", "classExactJoin.html", null ],
    [ "ExactJoinParallel", "classExactJoinParallel.html", null ],
    [ "simjoin_entitymatching.blocker.extract_formula.ExtractFormula", "classsimjoin__entitymatching_1_1blocker_1_1extract__formula_1_1ExtractFormula.html", null ],
    [ "Feature", "structFeature.html", null ],
    [ "FeatureArguments", "structFeatureArguments.html", null ],
    [ "FeatureEngineering", "classFeatureEngineering.html", null ],
    [ "FeatureIndex", "classFeatureIndex.html", null ],
    [ "FeatureUtils", "classFeatureUtils.html", null ],
    [ "simjoin_entitymatching.value_matcher.glove.Glove", "classsimjoin__entitymatching_1_1value__matcher_1_1glove_1_1Glove.html", null ],
    [ "GroupInterchangeable", "classGroupInterchangeable.html", null ],
    [ "hashValue", "structhashValue.html", null ],
    [ "SetJoin::invertedList", "structSetJoin_1_1invertedList.html", null ],
    [ "SetJoin::invIndexStruct", "structSetJoin_1_1invIndexStruct.html", null ],
    [ "KNNBlocker", "classKNNBlocker.html", null ],
    [ "MultiWriter", "classMultiWriter.html", null ],
    [ "simjoin_entitymatching.feature.feature_base.NewFeatureExtractor", "classsimjoin__entitymatching_1_1feature_1_1feature__base_1_1NewFeatureExtractor.html", null ],
    [ "simjoin_entitymatching.feature.feature_base.NewFeatures", "classsimjoin__entitymatching_1_1feature_1_1feature__base_1_1NewFeatures.html", null ],
    [ "OvlpRSJoin", "classOvlpRSJoin.html", null ],
    [ "OvlpRSJoinParallel", "classOvlpRSJoinParallel.html", null ],
    [ "OvlpSelfJoin", "classOvlpSelfJoin.html", null ],
    [ "OvlpSelfJoinParallel", "classOvlpSelfJoinParallel.html", null ],
    [ "OvlpUtil", "classOvlpUtil.html", null ],
    [ "OvlpUtilParallel", "classOvlpUtilParallel.html", null ],
    [ "PIndex", "structPIndex.html", null ],
    [ "PQComparison", "structPQComparison.html", null ],
    [ "simjoin_entitymatching.matcher.random_forest.RandomForest", "classsimjoin__entitymatching_1_1matcher_1_1random__forest_1_1RandomForest.html", null ],
    [ "Rule", "structRule.html", null ],
    [ "RuleReader", "classRuleReader.html", null ],
    [ "Sample", "classSample.html", null ],
    [ "Sampler", "classSampler.html", [
      [ "DownSampler", "classDownSampler.html", null ],
      [ "JacSampler", "classJacSampler.html", null ],
      [ "OvlpSampler", "classOvlpSampler.html", null ]
    ] ],
    [ "SamplerUtil", "classSamplerUtil.html", null ],
    [ "SetJoin", "classSetJoin.html", null ],
    [ "SetJoinParallel", "classSetJoinParallel.html", null ],
    [ "SetJoinParelledIndex", "structSetJoinParelledIndex.html", null ],
    [ "SetJoinUtil", "classSetJoinUtil.html", [
      [ "SetJoinParallelUtil", "classSetJoinParallelUtil.html", null ]
    ] ],
    [ "SimFuncs", "classSimFuncs.html", null ],
    [ "SimFuncsTemplate", "classSimFuncsTemplate.html", null ],
    [ "SimJoinBlocker", "classSimJoinBlocker.html", null ],
    [ "StringJoin", "classStringJoin.html", null ],
    [ "StringJoinParallel", "classStringJoinParallel.html", null ],
    [ "StringJoinUtil", "classStringJoinUtil.html", null ],
    [ "Table", "classTable.html", null ],
    [ "TableEntry", "structTableEntry.html", null ],
    [ "TFIDF", "classTFIDF.html", null ],
    [ "Tokenizer", "classTokenizer.html", null ],
    [ "TopK", "classTopK.html", null ],
    [ "simjoin_entitymatching.blocker.graph.TripartiteGraph", "classsimjoin__entitymatching_1_1blocker_1_1graph_1_1TripartiteGraph.html", null ],
    [ "WeightPair", "structWeightPair.html", null ],
    [ "WeightPairEdit", "structWeightPairEdit.html", null ],
    [ "simjoin_entitymatching.value_matcher.word2vec.Word2Vec", "classsimjoin__entitymatching_1_1value__matcher_1_1word2vec_1_1Word2Vec.html", null ]
];